INPUT_DIR = "data/test/videos"
OUTPUT_DIR = "data/test/pairs"

AUDIO_FRAME_LENGTH_SECS = 0.2
AUDIO_SAMPLE_DIFFERENT_SPEAKER_PROB = 0.7
AUDIO_SAMPLE_SILENCE_PROB = 1 - AUDIO_SAMPLE_DIFFERENT_SPEAKER_PROB

CHUNK_LENGTH_SECS = 3
CHUNK_NUM_FRAMES = 50
CHUNK_FPS = CHUNK_NUM_FRAMES / CHUNK_LENGTH_SECS
